### ISSUE TITLE
Invalid schema.json urls

### ISSUE THREAD

**Issue by theimpostor** [lostintangent/codeswing#72] opened 2022-08-27 14:34 UTC
While opening codeswing.json I see vscode report the following problem: `Unable to parse content from 'https://gist.githubusercontent.com/lostintangent/21727eab0d79c7b9fd0dde92df7b1f50/raw/schema.json': Parse error at offset 3.`. Looks like the gist url returns 404. In fact both schema urls mentioned in package.json appear to be invalid:

```
    "jsonValidation": [
      {
        "fileMatch": "codeswing.json",
        "url": "https://gist.githubusercontent.com/lostintangent/21727eab0d79c7b9fd0dde92df7b1f50/raw/schema.json"
      },
      {
        "fileMatch": "gallery.json",
        "url": "https://gist.githubusercontent.com/lostintangent/091c0eec1f6443b526566d1cd3a85294/raw/schema.json"
      }
    ],
```

**Comment by lostintangent** [comment] 2023-12-28 17:16
Closing as a duplicate of #57

**Closed by lostintangent** 2023-12-28 17:16 UTC
