### ISSUE TITLE
Exporting to CodePen.io

### ISSUE THREAD

**Issue by mattavery** [lostintangent/codeswing#88] opened 2024-02-17 20:53 UTC
When I try to "Export to CodePen" - my browser opens up to "https://codepen.io/pen/define" and the window just has the text "Bad Request".

Do I have to configure codeswing to use my codepen account or something for this to work?

**Comment by lostintangent** [comment] 2024-02-17 21:08
Hmm, this feature may have regressed based on a change to the codepen API. I'll try to take a look and see what is going on. Apologies for the issue!

**Comment by lostintangent** [comment] 2024-02-17 21:51
I just tried this out and everything seemed to work great for me. And I tried a few various languages just to double check.

Could you let me know which kind of swing you were seeing this failure with? And also, what OS/browser you're using? I confirmed that I'm using the latest CodePen APi correctly, but I want to confirm that I'm not missing some edge case. Thanks!

**Comment by mattavery** [comment] 2024-02-17 22:43
I'm on a Mac OS 14.3.1, and am a newbie to VS Code.
I had a simple swing with an index.html, style.css and script.js

I have an account on CodePen.io and was logged in. I've actually been using
codepen for years - and am excited to use vs code + codeswing to do the
same thing!

**Comment by lostintangent** [comment] 2024-02-17 22:58
Hmm ok. I'm also on macOS and I've tried an HTML/JS/CSS template with both Safari and Chrome, and it works beautifully. Out of curiosity, if you sign out of CodePen and try to export a swing from VS Code, does that work?

**Comment by mattavery** [comment] 2024-02-17 23:02
I just logged out of codepen, same thing - and I tried two different chrome
profiles. How can I send the command to safari instead?
I keep just getting "codepen.io/pen/define" sent to the location bar.
Is it maybe some sort of configuration issue I have to do in VS Code? Again
- I'm a newbie at it - first day!

**Comment by mattavery** [comment] 2024-02-17 23:05
If I go to "https://codepen.io/pen/define" manually, even when logged out,
I get an empty codepen setup with the html/css/js windows and the preview
window. When VSCode sends the command I just get a blank window with "Bad
Request" on the page.
[image: image.png]

**Comment by lostintangent** [comment] 2024-02-17 23:07
That CodePen URL is expected, but it seems like there's something erroring out when I send that endpoint the swing data. Could you try a brand new HTML/CSS/JS swing that has no code in it? I just want to confirm whether or not there's an issue with the code formatting when posting it to CodePen.

Also, is it possible you have any Chrome extensions that might be blocking anything?

**Comment by mattavery** [comment] 2024-02-17 23:16
ah - yeah - a fresh basic codeswing switched over to codepen just fine.
maybe my page is too complicated?

**Comment by lostintangent** [comment] 2024-02-17 23:19
If you're comfortable sharing the code with me, I'd love to take a look and see what might be going wrong. It might just be a character that I need to URL encode or something. And if you want to try to narrow it down, maybe try a blank swing and just test exporting with your HTML, JS and CSS separately? Since I'm guessing the issue is with just one of your files.

**Comment by mattavery** [comment] 2024-02-17 23:26
I've been going thru and adding my functions one by one - and of course the
last function I have makes it send the bad request.
Everything else works as expected - so I'll start debugging. Thanks for
being so responsive - I'll let you know how it goes!

**Comment by mattavery** [comment] 2024-02-17 23:36
I've narrowed it down to  "&nbsp;&nbsp;"
It works if I don't include those non-breaking space markers.

**Comment by mattavery** [comment] 2024-02-17 23:37
Even if the line is commented out, it doesn't seem to want to digest *&nbsp*

**Comment by lostintangent** [comment] 2024-02-18 00:58
Alright great, thanks for narrowing it down. I've got a fix and can publish an update later this evening.

**Comment by lostintangent** [comment] 2024-03-03 19:34
This is fixed in 0.0.23, so if you update from the marketplace, you should be good to go. Thanks!

**Closed by lostintangent** 2024-03-03 19:34 UTC

**Comment by mattavery** [comment] 2024-03-03 19:47
Awesome, thanks for the update!
